[project]
name = "google-play-store-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "numpy",
    "python-dateutil",
    "pytz",
    "six",
    "tzdata"
]
