[project]
name = "google-play-store-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "python-dateutil",
    "pytz",
    "six",
    "tzdata",
]
